services:
  - type: web
    name: bio-creator
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    plan: free
    envVars:
      - key: PORT
        value: 10000 